#!/usr/bin/env python3
"""Bundle JSON data into a single JS file so the site stays fully static.

Run from repo root:
    python scripts/bundle-data.py

Reads all .json from assets/data/ and bundles them into:
    assets/js/site-data.js  (defines window.SITE_DATA)

Top-level keys:
    topics          <- topics.json
    paths           <- learning-paths.json
    codeMap         <- code-map.json
    steps.<id>      <- <id>-steps.json  (e.g. scheduler-steps -> steps.scheduler)
    cases.<id>      <- <id>-cases.json  (e.g. parallelism-cases -> cases.parallelism)
    other.<stem>    <- any other .json file
"""
import json
import re
from pathlib import Path

_CORE = {"topics", "learning-paths", "code-map"}
_KEY_MAP = {"learning-paths": "paths", "code-map": "codeMap"}


def _to_camel(s: str) -> str:
    parts = s.split("-")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    data_dir = root / "assets" / "data"

    bundle: dict = {}
    steps: dict = {}
    cases: dict = {}
    other: dict = {}

    for jf in sorted(data_dir.glob("*.json")):
        stem = jf.stem
        data = json.loads(jf.read_text())
        if stem in _CORE:
            bundle[_KEY_MAP.get(stem, stem)] = data
        elif stem.endswith("-steps"):
            steps[_to_camel(stem[: -len("-steps")])] = data
        elif stem.endswith("-cases"):
            cases[_to_camel(stem[: -len("-cases")])] = data
        else:
            other[_to_camel(stem)] = data

    if steps:
        bundle["steps"] = steps
    if cases:
        bundle["cases"] = cases
    if other:
        bundle["other"] = other

    out = root / "assets" / "js" / "site-data.js"
    payload = json.dumps(bundle, ensure_ascii=False, indent=2)
    out.write_text(
        "// Auto-generated by scripts/bundle-data.py. Do not edit by hand.\n"
        f"window.SITE_DATA = {payload};\n"
    )
    print(f"wrote {out.relative_to(root.parent)} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
